simplenet_default_model_params =  {"backbone": "wideresnet50",
                                    "layers_to_extract_from": ["layer2", "layer3"],
                                    "device": "cuda:3",
                                    "input_size": 256,
                                    "pretrain_embed_dimension": 1536, 
                                    "target_embed_dimension": 1536, 
                                    "patchsize": 3, 
                                    "patchstride": 1,
                                    "epochs" : 40,
                                    "embedding_size": 256, 
                                    "aed_meta_epochs": 1,
                                    "gan_epochs": 1,
                                    "noise_std": 0.015,
                                    "mix_noise": 1,
                                    "noise_type": "GAU",
                                    "dsc_layers": 2,
                                    "dsc_hidden": 1024,
                                    "dsc_margin": .5,
                                    "dsc_lr": 0.0002,
                                    "train_backbone": False,
                                    "auto_noise": 0,
                                    "cos_lr": True,
                                    "lr": 1e-3,
                                    "pre_proj": 1,
                                    "proj_layer_type": 0,
}